In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg as la
import seaborn as sns
import pandas as pd

In [3]:
x1 = np.random.normal(0, 1, 1000)
x2=x1+np.random.normal(0, 3, 1000)
x3=2*x1+x2
print(x1.shape,x2.shape,x3.shape)

(1000,) (1000,) (1000,)


In [8]:
df=np.array([x1,x2,x3])
print(df.shape)
df

(3, 1000)


array([[  0.71376886,  -0.95676023,   0.70860059, ...,   0.84968104,
          0.07963463,   1.01322951],
       [ -0.21191865, -10.47385791,   4.94529664, ...,   0.85450949,
          0.94616566,   1.07588597],
       [  1.21561907, -12.38737837,   6.36249783, ...,   2.55387157,
          1.10543492,   3.10234499]])

In [9]:
np_cov = np.cov(df)


In [10]:
U, S, Vt = np.linalg.svd(df)
scale_factor = 3
# Rescale the SVD spectrum to get the eigenvalues
l_svd = S**2/(1000-1)
# The matrix U already contains the eigenvectors
V_svd = U
print(V_svd)
print(l_svd)

[[-0.10980675  0.56681197 -0.81649658]
 [-0.5843933  -0.70129723 -0.40824829]
 [-0.80400681  0.43232671  0.40824829]]
[2.96989445e+01 1.90040244e+00 1.29683792e-30]


In [11]:
l, v = la.eig(np_cov)
print('eigenvalues')
print(l)
print('realeigenvalues')
print(np.real_if_close(l))
print('eigenvectors')
print(v)

eigenvalues
[ 2.96989443e+01+0.j -1.31298132e-15+0.j  1.89177196e+00+0.j]
realeigenvalues
[ 2.96989443e+01 -1.31298132e-15  1.89177196e+00]
eigenvectors
[[-0.10980573 -0.81649658  0.56681217]
 [-0.58439457 -0.40824829 -0.70129618]
 [-0.80400603  0.40824829  0.43232816]]


compare eginvectors in both approaches and they are the same;

In [12]:
U, s, Vt = la.svd(np_cov)
print('u:',U)
print(np.real_if_close(s))
print('s:',s)

u: [[-0.10980573  0.56681217 -0.81649658]
 [-0.58439457 -0.70129618 -0.40824829]
 [-0.80400603  0.43232816  0.40824829]]
[2.96989443e+01 1.89177196e+00 6.31285754e-16]
s: [2.96989443e+01 1.89177196e+00 6.31285754e-16]


In [28]:

for li, vi in zip(l_svd,V_svd.T ):
    print("Eigenvalue:", li, ",\teigenvector:", vi)

print(V_svd.T[0,:],V_svd[1,:])
new=np.array([V_svd.T[0,:],V_svd.T[1,:]])
print(new)

Eigenvalue: 29.69894454310397 ,	eigenvector: [-0.10980675 -0.5843933  -0.80400681]
Eigenvalue: 1.9004024402037556 ,	eigenvector: [ 0.56681197 -0.70129723  0.43232671]
Eigenvalue: 1.296837916493043e-30 ,	eigenvector: [-0.81649658 -0.40824829  0.40824829]
[-0.10980675 -0.5843933  -0.80400681] [-0.5843933  -0.70129723 -0.40824829]
[[-0.10980675 -0.5843933  -0.80400681]
 [ 0.56681197 -0.70129723  0.43232671]]


In [23]:
#ex2
noises = np.random.normal(loc=0, scale=1/50, size=(3, 1000, 10))
x_noise = df + np.sum(noises, axis = 2)
print(x_noise.shape)

(3, 1000)


In [22]:
U2, S2, Vt2 = np.linalg.svd(x_noise)
scale_factor = 3
l_svd2 = S2**2/(1000-1)
V_svd2 = U2
print(V_svd2)
print(l_svd2)

[[-0.10977188  0.56704959 -0.81633627]
 [-0.58380847 -0.70148313 -0.40876533]
 [-0.80443633  0.43171309  0.40805147]]
[2.96786818e+01 1.89821668e+00 4.09222589e-03]


In [26]:
l2, v2 = la.eig(np.cov(x_noise))
print(l2)
print(np.real_if_close(l))
print(v2)
X = np.dot(v.T, df)
print(X)
print(X.shape)

eigenvalues
[2.97054232e+01+0.j 3.88485504e-03+0.j 1.89264479e+00+0.j]
realeigenvalues
[ 2.96989443e+01 -1.31298132e-15  1.89177196e+00]
eigenvectors
[[-0.11032381 -0.81632676  0.56695615]
 [-0.58390742 -0.40838026 -0.70162504]
 [-0.80428899  0.40845585  0.43160518]]
[[-9.31896861e-01  1.61854503e+01 -8.08329950e+00 ... -2.64599869e+00
  -1.45045475e+00 -3.23430440e+00]
 [ 2.05363400e-16  2.50048721e-15 -1.14467891e-15 ... -5.31901743e-18
  -2.66258268e-16  1.32960637e-16]
 [ 1.07873697e+00  1.44756063e+00 -3.15787189e-01 ...  9.86455917e-01
  -1.40493831e-01  1.16102721e+00]]
(3, 1000)


ex3 optional
